version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jaf-edge-redirect"
s3_bucket = "jvb-code-useast1"
s3_prefix = "SAM/jaf-edge-redirect"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
# parameter_overrides = ""
image_repositories = []
