AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'TS edge redirect'

Parameters:
  DEBUG:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"

Globals:
  Function:
    Timeout: 1
    MemorySize: 128
    Runtime: nodejs14.x
    Environment:
      Variables:
        DEBUG: !Ref DEBUG

Resources:
  EdgeRedirectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: index.handler

Outputs:
  EdgeRedirectFunction:
    Description: Redirect apex to www
    Value: !Ref EdgeRedirectFunction